### PR TITLE
Refactoring to Support Pagination 

### PR DESCRIPTION
**Pull request by stephen-ta**
*This will be a major version update as it contains breaking changes*

* scan()'s `paramVersion` param was replaced with an `options` param that is an object containing any of the following: version, limit, lastKey -- the last two will be used to support pagination capabilities
* The output of scan() is no longer just the results, but rather the full response from DynamoDB that contains the `Items` (i.e. results) but also information such as `LastKeyEvaluated` or `Count`, etc. which would be used to support pagination as well as provide flexibility down the road for more extensibility
* readPaginate() was added
* Replaces the Makefile with DevLab

### CODE REVIEW

**Comment by Fluidbyte** [comment]
Looks good from what I can see. A couple thoughts related to process:
1. We could/should add a `circle.yml` and get it building on CCI. You can pull one from one of our other hub modules.
2. We don't need to include the build, you can `gitignore` the build dir and in `package.json` set a `scripts.prepublish` and `files`. Again, see one of the modules we use on hubs for an example.

I'll look to @TomFrost for guidance on the dynamo-specific code, but it looked good to me.

**Comment by stephen-ta** [comment]
So after looking at this again, one thing doesn't feel right -- and that is `readPaginate` is essentially a copy of `getItemById` with pagination support. Perhaps it would be better to remove `getItemById` and then rename `readPaginate` to `getItemById`. Essentially, upgrading `getItemById` to have pagination support much like upgrading `scan` was done.

The only concession is that anyone calling `read`, which deterministically calls `getItemById`, would not be able to call `read` with pass-through pagination support. And instead would have to call `getItemById` directly when wanting to set a `limit` or `lastKey` -- to support pagination.

**Comment by stephen-ta** [comment]
Nevermind, that ^ (last comment) won't work because that would essentially change the output of `read` when it calls `getItemById`. Therefore, the separate `readPaginate` should stay.

**Comment by Fluidbyte** [comment]
:accept:

**Pull request merged**
